### ISSUE TITLE
webstorm2021上，一直报错

### ISSUE THREAD

**Issue by coolkidxu** [Rickykurt/VantPlugin#11]
![image](https://user-images.githubusercontent.com/74520733/118059323-d98f3300-b3c2-11eb-97af-8b42a83dba0f.png)

**Comment by GuiYangGan** [comment]
![image](https://user-images.githubusercontent.com/24996770/123586858-f28b6080-d817-11eb-9664-2bfa9f8953bc.png)

**Comment by mmfei** [comment]
我的是 从 npm 14 升级到16 就出现了 , 14正常的

**Comment by Rickykurt** [comment]
vant官方已经提供了代码编辑器的代码提示及补全功能，此插件将不再更新，详情参见：https://github.com/youzan/vant/pull/5900
具体代码在node_modules中vant/vetur下
