### ISSUE TITLE
插件在最新版本的IDEA当中会提示 所有的vant标签为unknown tag

### ISSUE THREAD

**Issue by QQ853695231** [Rickykurt/VantPlugin#2]
![image](https://user-images.githubusercontent.com/22435948/56856902-842c8880-6997-11e9-8c77-eab0ac002928.png)

IDEA 版本 2019.1.1

**Comment by guowenzhuang** [comment]
> ![image](https://user-images.githubusercontent.com/22435948/56856902-842c8880-6997-11e9-8c77-eab0ac002928.png)
> 
> IDEA 版本 2019.1.1

我也有同样的情况 我的版本是2019.1.3

**Comment by TY-LIU** [comment]
同样的情况 2019.1.2

**Comment by zhihui-shi** [comment]
同样的情况 2018.3.2

**Comment by finalz** [comment]
please fix, thanks

**Comment by Rickykurt** [comment]
已修复，官方的新版插件在审核中，需要2工作日，着急的话，可以先安装VantPlugin.zip。
感谢大家关注
