### ISSUE TITLE
idea插件开发

### ISSUE THREAD

**Issue by transtone** [Rickykurt/VantPlugin#3]
你好，因为 vuejs 的插件不能装在 android studio 中，就想自己编译一个。

看了一些教程却没有入门，所以问一下仁兄看的什么资料，idea是如何限制插件的安装的，如果想装，需要怎么改动。

谢谢。

**Comment by Rickykurt** [comment]
其实我没看啥资料，主要就是参考了  https://github.com/jiaolong1021/ElementPlugin 
再就是 idea 官方的资料 https://www.jetbrains.org/intellij/sdk/docs/basics/getting_started.html
里面很多细节的东西就需要自己跟api看实现了
