### ISSUE TITLE
ctrl+q唤出文档  无内容 且和ElementPlugin有冲突

### ISSUE THREAD

**Issue by xiang473535976** [Rickykurt/VantPlugin#4]
1.只安装ElementPlugin  ctrl+q能正确的请求出数据
![image](https://user-images.githubusercontent.com/18111614/62097797-af868280-b2ba-11e9-8108-e79b67c94416.png)

2.只安装VantPlugin  能唤出文档界面  无数据
![image](https://user-images.githubusercontent.com/18111614/62098037-6551d100-b2bb-11e9-8ea0-752bdbd5a646.png)
3.同时安装ElementPlugin和VantPlugin          只是能唤出文档界面  两个插件都无数据了

**Comment by Rickykurt** [comment]
已做修复

**Comment by xiang473535976** [comment]
> 已做修复

同时开启 ElementPlugin不能请求文档数据   VantPlugin能请求
